### ISSUE TITLE
Can author kindly upload processed data?

### ISSUE THREAD

**Issue by HantaoShu** [jiaxchen2-c/DeepDRIM#5]
Hi Jiaxing Chen,  recently I read your paper DeepDRIM, can you upload demo data (for example, pairs_for_predict_file, geneName_map_file, TF_divide_pos_file used in your paper)for reproduce the result of your paper.

**Comment by jiaxchen2-c** [comment]
Thank you for your message.
You can download the demo data at the following link:
https://zenodo.org/record/4475471#.YSph2tOA79F
While https://zenodo.org/record/4475471/files/data_evaluation.zip?download=1
is for evaluation in the eight cell lines.
The data are collected from the two links (https://github.com/xiaoyeye/CNNC
 , https://doi.org/10.5281/zenodo.3378975.) and converted to the format
that is suitable for our model.
For example,
"single_cell_type/training_pairshESC.txt" is the whole
"pairs_for_predict_file" converted from the original file for the hESC.
"single_cell_type/training_pairshESC.txt_for_generate" is the
"pairs_for_predict_file"
used in our paper, for we did the experiment on the randomly selected TFs.
"single_cell_type/training_pairshESC.txtTF_divide_pos.txt" is the
"TF_divide_pos_file".

In addition,
https://zenodo.org/record/4475471/files/data_COVID-19.zip?download=1 is for
the case study of B cells in COVID19 demonstrated in the paper.

Please let me know if you have any questions.

Bests,
Jiaxing


HantaoShu ***@***.***> 於 2021年8月29日 週日 上午12:14寫道：

**Comment by HantaoShu** [comment]
Thanks for your help, I closed this issue.
